version: "3.8"

services:

  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}

    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app

    working_dir: /var/www

    volumes:
      - .:/var/www

    ports:
      - "8000:8000"

    command: php artisan serve --host=0.0.0.0 --port=${PORT:-8000}

    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy

  database:
    image: mysql:8.0

    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_api
      MYSQL_USER: laravel
      MYSQL_PASSWORD: ""

    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  queue:
    build:
      context: .
    container_name: laravel-queue
    environment:
      - CONTAINER_ROLE=queue
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - redis
    command: php artisan queue:work --queue=redis -vvv --tries=3 --timeout=18

  redis:
    image: redis:alpine

    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "${REDIS_PASSWORD}"
      ]

    ports:
      - "6379:6379"

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-a",
          "${REDIS_PASSWORD}",
          "ping"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:

